#!/bin/bash

# GROOVYARCADE details
export GA_VERSION=testing
if [[ ! -z ${CI_COMMIT_TAG} ]] ; then
  GA_VERSION=${CI_COMMIT_TAG}
elif [[ ! -z ${CI_COMMIT_REF_SLUG} && ${CI_COMMIT_REF_SLUG} != "master" ]] ; then
  GA_VERSION=${CI_COMMIT_REF_SLUG}
fi
